### ISSUE TITLE
Problem with font kit dependency restructure

### ISSUE THREAD

**Issue by ceugster** [schoero/SwissQRBill-browser-example#15]
Hi 
I try to use this project. After having built the project I run the two examples pdf.html and svg.html. While svg.html runs the pdf.html example produces an exception in the module's fontkit node_modules/restructure's EncodeStream:
Uncaught TypeError: t is undefined
    7611 EncodeStream.js:5
    i EncodeStream.js:18
    7611 EncodeStream.js:147
    7611 EncodeStream.js:151

Sincerely Christian Eugster

**Comment by schoero** [comment]
Hi Christian

I can't reproduce your error. If I follow the steps in the readme `pdf.html` and `svg.html` both load without any errors.

What operating System, Browser and Node.js version are you using?

**Comment by ceugster** [comment]
Hallo Roger

Ich arbeite mit MacOs Ventura, als Browser verwende ich firefox ( weil da die entsprechenden Werkzeuge vorhanden sind) und die neueste Version node.js (19.7.0).

Herzliche Grüsse

Christian

**Comment by schoero** [comment]
Danke für die Infos

Ich weiss leider gerade nicht wie ich weiterhelfen kann. Ich verwende ebenfalls MacOS Ventura und ich habe es soeben nochmals mit Firefox und Node.js 19.7.0 getestet. Das funktioniert bei mir weiterhin ohne Probleme.

Ich hab inzwischen noch die dependencies aktualisiert. Vielleicht hilft das wenn du nochmals einen git pull machst und alles nochmals erneut installierst:

```bash
# ./SwissQRBill-browser-example
rm -r node_modules
git pull
npm i
npm start
```

Ist das die komplette Fehlermeldung? Ich finde nämlich im Source Code von `node_modules/restructure/src/EncodeStream.js` keine Variable mit dem namen `t`.

**Comment by ceugster** [comment]
Hab ich gemacht.

Nun habe ich folgende Meldungen:

Diese Seite befindet sich im Kompatibilitätsmodus (Quirks). Das Seitenlayout kann beeinflusst werden. Verwenden Sie für den Standardmodus "<!DOCTYPE html>".
pdf.html <http://127.0.0.1:8000/pdf.html>
[HMR] Waiting for update signal from WDS... log.js:24 <webpack://SwissQRBill/node_modules/webpack/hot/log.js>
Uncaught TypeError: document.body is null
    createContainer overlay.js:142
    ensureOverlayExists overlay.js:160
    show overlay.js:182
    showOverlay overlay.js:224
    send fsm.js:54
    send fsm.js:52
    createOverlay overlay.js:236
    listenToRuntimeError runtime-error.js:26
    createOverlay overlay.js:228
    true index.js:110
    Webpack 5
overlay.js:142 <webpack://SwissQRBill/node_modules/webpack-dev-server/client/overlay.js>
Uncaught TypeError: parent is undefined
    __extends EncodeStream.js:5
    EncodeStream EncodeStream.js:18
    js EncodeStream.js:147
    js EncodeStream.js:151
    Webpack 27
EncodeStream.js:5:175 <webpack://SwissQRBill/node_modules/restructure/src/EncodeStream.js>
GEThttp://127.0.0.1:8000/favicon.ico[HTTP/1.1 404 Not Found 0ms] <> 

Scheint im Webpack zu sein. Und wie gesagt: svg.html funktioniert problemlos.

​

**Comment by schoero** [comment]
Hallo Christian

Dein Firefox fällt in einen Kompatibilitätsmodus weil der HTML DocType tag gefehlt hat. Möglicherweise liegt es daran.
Ich habe den fehlenden Tag in `pdf.html` hinzugefügt. Kannst du nochmals pullen und testen?

```bash
# ./SwissQRBill-browser-example
git pull
npm start
```

Falls es auch danach nicht geht, funktioniert es in einem anderen Browser wie Safari oder Google Chrome?

**Comment by ceugster** [comment]
Hallo Roger

Ich bin wie von Dir angegeben vorgegangen und habe auch unter firefox, safari und chrome getestet. Ich erhalte jetzt folgende Fehlermeldung:

Uncaught TypeError: Cannot read properties of undefined (reading 'prototype')
    at EncodeStream.js:5:200
    at EncodeStream.js:18:5
    at Object.<anonymous> (EncodeStream.js:15:18)
    at 3228 (EncodeStream.js:151:4)
    at t (bootstrap:19:32)
    at Object.<anonymous> (index.js:5:26)
    at 7887 (index.js:43:4)
    at t (bootstrap:19:32)
    at 2920 (index.js:5:25)
    at t (bootstrap:19:32)

Siehe auch screenshots unten:
￼

￼

**Comment by ceugster** [comment]
…svg.html funktioniert nach wie vor

**Comment by schoero** [comment]
Die Screenshots kann ich auf GitHub leider nicht sehen.

Nur damit wir uns richtig verstehen: Du hast die Repository wie im [Readme](https://github.com/schoero/SwissQRBill-browser-example) zuerst mit `git clone https://github.com/schoero/SwissQRBill-browser-example.git` geklont, dann mit  `cd SwissQRBill-browser-example && npm install` installiert und im Anschluss mit `npm run start` gestartet? Du hast sonst nichts geändert?

**Comment by ceugster** [comment]
Ja, ich clone das repository, mache nem install und npm run start und ändere nichts am code. Entschuldige, nachfolgend die Screenshots.
<img width="1196" alt="Bildschirm­foto 2023-03-21 um 18 54 11" src="https://user-images.githubusercontent.com/1636301/226821362-42b72781-87d4-4970-ac06-a6a5560f147a.png">
<img width="2558" alt="Bildschirm­foto 2023-03-21 um 18 46 46" src="https://user-images.githubusercontent.com/1636301/226821386-d6e4a06b-8d8c-44a2-b16a-59c2e18354d2.png">

**Comment by ceugster** [comment]
Hallo Roger

Ich hatte Gelegenheit swissqrbill-browser-example unter windows 11 zu testen. Da funktioniert es mit dem aktuellen Code. Unter Mac Ventura nicht.

Herzliche Grüsse Christian
